<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount Sold' => 'Cantidad Vendida',
    'Are you sure you want to delete this item?' => 'Está seguro de que desea eliminar este ìtem?',
    'Create' => 'Crear',
    'Create Freights' => 'Crear Transportador',
    'Create Packagescontrol' => 'Crear Control de Paquetes',
    'Create Parameters' => 'Crear Parametros',
    'Create Products' => 'Crear Productos',
    'Create Units Measures' => 'Crear Unidad de Medida',
    'Create User' => 'Crear Usuario',
    'Created At' => 'Creado en',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Freights' => 'Transportadores',
    'ID' => 'ID',
    'Id Freight' => 'Id Transportador',
    'Id Order' => 'Id Orden',
    'Id Package' => 'Id Paquete',
    'Id Parameter' => 'Id Parametro',
    'Id Product' => 'Id Producto',
    'Id Unit' => 'Id Unidad',
    'Id User' => 'Id Usuario',
    'Initial Date' => 'Fecha Inicial',
    'Math' => 'Matemática',
    'Modify Date' => 'Fecha de Modificación',
    'Name' => 'Nombre',
    'Name Name' => 'Nombre Nombre',
    'Name Unit' => 'Nombre Unidad',
    'Observations' => 'Observaciones',
    'Package State' => 'Estado del Paquete',
    'Packagescontrols' => 'Control de Paquetes',
    'Parameters' => 'Parametros',
    'Price' => 'Precio',
    'Products' => 'Productos',
    'Quantity Purchased' => 'Cantidad Comprada',
    'Remaining Amount' => 'Cantidad Restante',
    'Reset' => 'Resetear',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'Taxes' => 'Impuestos',
    'Telephone' => 'Teléfono',
    'Units Measures' => 'Unidades de Medida',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado en',
    'Users' => 'Usuarios',
    'Address' => '@@@@',
    'Auth Key' => '@@@@',
    'Email' => '@@@@',
    'Last Name' => '@@@@',
    'Password Hash' => '@@@@',
    'Password Reset Token' => '@@@@',
    'Status' => '@@@@',
    'Username' => '@@@@',
];
