<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Dirección',
    'Amount Sold' => 'Cantidad Vendida',
    'Are you sure you want to delete this item?' => 'Está seguro de que desea eliminar este ítem?',
    'Auth Key' => 'Llave de Autenticación',
    'Avatar' => 'Avatar',
    'Create' => 'Crear',
    'Create Freights' => 'Crear Transportador',
    'Create Packagescontrol' => 'Crear Control de Paquetes',
    'Create Parameters' => 'Crear Parametros',
    'Create Products' => 'Crear Productos',
    'Create Units Measures' => 'Crear Unidades de Medida',
    'Create User' => 'Crear Usuario',
    'Created At' => 'Creado en',
    'Created_at' => 'Creado en ',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Email' => 'Email',
    'Freights' => 'Transportador',
    'ID' => 'Id',
    'Id' => 'Id',
    'Id Freight' => 'Id Transportador',
    'Id Image' => 'Id Image',
    'Id Order' => 'Id Orden',
    'Id Package' => 'Id Paquete',
    'Id Parameter' => 'Id Parametro',
    'Id Product' => 'Id Producto',
    'Id Unit' => 'Id Unidad',
    'Id User' => 'Id Usuario',
    'Image' => 'Imagen',
    'Last Name' => 'Apellidos',
    'Math' => 'Matemática',
    'Name' => 'Nombre',
    'Name Unit' => 'Nombre Unidad',
    'Observations' => 'Observación',
    'Package State' => 'Estado del Paquete',
    'Packagescontrols' => 'Control de Paquetes',
    'Parameter Code' => 'Código del Parametro',
    'Parameters' => 'Parametros',
    'Password Hash' => 'Clave Hash',
    'Password Reset Token' => 'Token para reiniciar la clave',
    'Price' => 'Precio',
    'Products' => 'Productos',
    'Quantity Purchased' => 'Cantidad Comprada',
    'Remaining Amount' => 'Cantidad que queda',
    'Reset' => 'Resetear',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'Status' => 'Estado',
    'Taxes' => 'Impuestos',
    'Telephone' => 'Teléfono',
    'Units Measures' => 'Unidades de Medida',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado en',
    'Updated_at' => 'Actualizado en',
    'Username' => 'Usuario',
    'Users' => 'Usuario',
    'created_at' => 'Creado en',
    'updated_at' => 'Actualizado en',
];
