<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Dirección',
    'Are you sure you want to delete this item?' => 'Está seguro de que desea eliminar este ìtem?',
    'Auth Key' => '',
    'Create' => 'Crear',
    'Create User' => 'Crear Usuario',
    'Created At' => 'Creado en',
    'Delete' => 'Borrar',
    'Email' => 'Correo Electrónico',
    'ID' => 'Id',
    'Last Name' => 'Apellidos',
    'Name' => 'Nombre',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Reset' => 'Resetear',
    'Search' => 'Buscar',
    'Status' => 'Estado',
    'Telephone' => 'Teléfono',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado en',
    'Username' => '',
    'Users' => 'Usuario',
];
