<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Está seguro en eliminar este ítem?',
    'Create' => 'Crear',
    'Create Detailorders' => 'Crear Detalle de la Orden',
    'Create Orders' => 'Crear Ordenes',
    'Create Products' => 'Crear Productos',
    'Date' => 'Fecha',
    'Date Order' => 'Fecha de la Orden',
    'Delete' => 'Borrar',
    'Detailorders' => 'Detalle de las Ordenes',
    'Id Detail Order' => 'Id Detalle de la Orden',
    'Id Order' => 'Id Orden',
    'Id Product' => 'Id Producto',
    'Id User' => 'Id Usuario',
    'Observation Detailorder' => 'Observación Detalle',
    'Observation Order' => 'Observación de la Orden',
    'Orders' => 'Ordenes',
    'Packagescontrols' => 'Control de paquetes',
    'Price' => 'Precio',
    'Product Name' => 'Nombre del Producto',
    'Products' => 'Productos',
    'Quantity Purchased' => 'Cantidad Comprada',
    'Reset' => 'Resetear',
    'Search' => 'Busqueda',
    'State' => 'Estado',
    'State Code' => 'Código Estado',
    'Total Value' =>  'Valor Total',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'created_at' => 'Creado en',
    'updated_at' => 'Actualizado en',
];
